Arts 2021 2022
UW-Path/DataParsing pull request #30
Opened 2021-09-04 01:48 UTC by b47huang

No Changes needed, just updated the ParseProgram file to include the 2021-2022 parser.

2021-09-05 18:46 UTC, haowei99 requested changes

2021-09-05 18:46 UTC, haowei99 commented on ProgramParsing/Arts/ParseProgram.py
> +    main(parsers, files, "Arts", True)
same here do we want True?

2021-09-06 21:32 UTC, b47huang reviewed
All done Hao Wei, I think we are good to merge Arts.

2021-09-06 21:32 UTC, b47huang commented on ProgramParsing/Arts/ParseProgram.py
> +    main(parsers, files, "Arts", True)
yep will fix

2021-09-06 23:29 UTC, haowei99 approved these changes

2021-09-07 00:17 UTC, merged